const MIXDM_PRODUCTS = [
  {
    id: 1,
    name: "Vestido Midi Floral Manga Longa",
    category: "Vestidos",
    tag: "-30%",
    price_current: 89.90,
    price_original: 129.90,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800&auto=format&fit=crop",
    description: "Vestido midi em tecido leve, estampa floral e manga longa. Um curinga para o dia a dia que também funciona em ocasiões mais especiais.",
    affiliate_url: "#",
    commission: 30,
    rating: 4.5,
    reviews_count: 328,
    spotlight: true,
    last_checked_at: new Date().toISOString()
  },
  {
    id: 2,
    name: "Sandália Salto Fino Nude",
    category: "Calçados",
    tag: "Novo",
    price_current: 119.90,
    price_original: null,
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=800&auto=format&fit=crop",
    description: "Sandália de salto fino na cor nude, fácil de combinar com looks casuais e de festa. Solado confortável para uso prolongado.",
    affiliate_url: "#",
    commission: 25,
    rating: 4.3,
    reviews_count: 156,
    spotlight: true,
    last_checked_at: new Date().toISOString()
  },
  {
    id: 3,
    name: "Bolsa Transversal Couro Ecológico",
    category: "Bolsas",
    tag: "-20%",
    price_current: 79.90,
    price_original: 99.90,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop",
    description: "Bolsa transversal em couro ecológico, compacta e com compartimentos internos para organizar o essencial.",
    affiliate_url: "#",
    commission: 20,
    rating: 4.7,
    reviews_count: 512,
    spotlight: true,
    last_checked_at: new Date().toISOString()
  },
  {
    id: 4,
    name: "Blazer Alfaiataria Feminino",
    category: "Roupas",
    tag: "-15%",
    price_current: 149.90,
    price_original: 179.90,
    image: "https://images.unsplash.com/photo-1551163943-3f6a855d1153?q=80&w=800&auto=format&fit=crop",
    description: "Blazer de alfaiataria com caimento reto, ideal para compor looks de trabalho ou eventos mais formais.",
    affiliate_url: "#",
    commission: 35,
    rating: 4.6,
    reviews_count: 243,
    spotlight: true,
    last_checked_at: new Date().toISOString()
  },
  {
    id: 5,
    name: "Conjunto Tricot Cropped + Saia",
    category: "Conjuntos",
    tag: "Novo",
    price_current: 139.90,
    price_original: null,
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop",
    description: "Conjunto em tricot com cropped e saia midi, perfeito para um look moderno e confortável.",
    affiliate_url: "#",
    commission: 28,
    rating: 4.8,
    reviews_count: 89,
    spotlight: false,
    last_checked_at: new Date().toISOString()
  },
  {
    id: 6,
    name: "Calça Jeans Skinny Cintura Alta",
    category: "Calças",
    tag: "-25%",
    price_current: 69.90,
    price_original: 89.90,
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=800&auto=format&fit=crop",
    description: "Calça jeans skinny com cintura alta, modelagem que valoriza a silhueta e conforto no dia a dia.",
    affiliate_url: "#",
    commission: 32,
    rating: 4.4,
    reviews_count: 671,
    spotlight: false,
    last_checked_at: new Date().toISOString()
  },
  {
    id: 7,
    name: "Top Fitness com Bojo",
    category: "Fitness",
    tag: "Novo",
    price_current: 49.90,
    price_original: null,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=800&auto=format&fit=crop",
    description: "Top fitness com bojo removível, alças ajustáveis e tecido que proporciona conforto durante os treinos.",
    affiliate_url: "#",
    commission: 22,
    rating: 4.2,
    reviews_count: 198,
    spotlight: false,
    last_checked_at: new Date().toISOString()
  },
  {
    id: 8,
    name: "Calça Legging Cós Alto",
    category: "Fitness",
    tag: "-10%",
    price_current: 59.90,
    price_original: 79.90,
    image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?q=80&w=800&auto=format&fit=crop",
    description: "Legging de cós alto com compressão suave, ideal para academia e uso casual.",
    affiliate_url: "#",
    commission: 40,
    rating: 4.6,
    reviews_count: 445,
    spotlight: false,
    last_checked_at: new Date().toISOString()
  }
];
